### ISSUE TITLE
[PE-D] [Exception Handling] Exception for unspecified attribute

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113-F12-2/tp#100]
Error message for unspecified attribute does not indicate the attribute to be changed.

![image.png](https://raw.githubusercontent.com/timchang27/ped/main/files/dc4e1b28-54cd-4929-a362-20687793548c.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: timchang27/ped#1

**Comment by shunyao643** [comment]
Parser did not parse `.`. Will be fixed in v2.1
