### ISSUE TITLE
[PE-D] FeatureFlaw - Auto Save

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113-F12-2/tp#108]
It is better to have auto save so that user wouldn't lose any if the program clashes.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: hlwang56/ped#9

**Comment by shunyao643** [comment]
Originally, this was not implemented as the entire file will need to be rewritten every time the save occurs. 

After reconsidering the auto-save and its efficiency, we will have it auto save every 5 commands, regardless of whether any actual changes happened.
