### ISSUE TITLE
Wrong error message when wrong tags are used for update command

### ISSUE THREAD

**Issue by yuhaochua** [AY2122S2-CS2113-F12-2/tp#132]
Prerequisites: run ``add n/`SpeakerB` s/`S1404115ASF` t/`Speaker` c/`1000` pf/`Loud_Technologies` pd/`2022-02-23` ``

![image](https://user-images.githubusercontent.com/58723008/162473070-32602611-006b-45ad-90b5-10e645c954dc.png)

Test input: ``update s/`S1404115ASF` rand/`SpeakerC` c/`2510` pd/`2022-08-21` ``
When executing update command, providing a wrong tag after the serial number seems to give a wrong error message. 

![image](https://user-images.githubusercontent.com/58723008/162473563-42cea203-8cd4-4357-b145-a5594a659e08.png)

Test input: ``update s/`S1404115ASF` c/`2510` rand/`SpeakerC` pd/`2022-08-21` ``
When the wrong tag is placed after another tag, the update goes through without any error and ignores whatever tag was before the wrong tag.

![image](https://user-images.githubusercontent.com/58723008/162474626-adf62f9a-f86f-4fd6-aa1d-66d6a6463186.png)

Test input: ``update s/`S1404115ASF` name/`SpeakerC` c/`2510` pd/`2022-08-21` ``
Strangely enough, if `name`  tag is used instead of `rand` tag after serial number, the update goes through.

**Comment by shunyao643** [comment]
Seems like I've found the issue - I was using the old logic of checking against the next regex when the new backtick approach allows for a less restrictive match.
