### ISSUE TITLE
App crashes when using list command, and specifying a type which does not exist

### ISSUE THREAD

**Issue by yuhaochua** [AY2122S2-CS2113-F12-2/tp#65]
Initially, I thought that the app crashed because I did not use uppercase when specifying the equipment type. After that I realised it was just any input which is not a value of the EquipmentType enumerator. I'll fix this, but maybe @shunyao643 can still implement the part under parser to accept lower case for this too?

**Comment by shunyao643** [comment]
Can you be more specific as to what input you tried that resulted in the bug? I'll work off it to see how it can be fixed.

**Comment by yuhaochua** [comment]
It was because I did not catch the IllegalArgumentException which happens when I try to list an EquipmentType which does not exist. I am able to fix it already, but was suggesting maybe you can extend the lowercase support when specifying EquipmentType to the list command as well!

**Comment by shunyao643** [comment]
This is the fix expected, yes?

**Comment by yuhaochua** [comment]
Yes, that is the fix expected, thank you!
