### ISSUE TITLE
[PE-D] "add" command accepts an invalid date. 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113-F12-2/tp#82]
![image.png](https://raw.githubusercontent.com/zhenster/ped/main/files/e39e13f2-55c9-4f13-87e6-6b742666c956.png)
The application accepts a date that is in an invalid format. Perhaps you could consider attempting to parse the user's input into a Date object and throwing an exception if the input is not a valid date. Alternatively, you could force the user to enter a date in a certain format (YYYY-MM-DD) and throw an exception if it's not in this format. 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: zhenster/ped#1

**Comment by Bryan-BC** [comment]
Duplicate of #103
